# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goscaffold < Formula
  desc "Scaffold Go projects with composable layers"
  homepage "https://github.com/jholm117/goscaffold"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.1.0/goscaffold_0.1.0_darwin_amd64.tar.gz"
      sha256 "087aa6883cde8289258c51a1b1c536391f604a374ea3c05d1b9c40095ef42164"

      define_method(:install) do
        bin.install "goscaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.1.0/goscaffold_0.1.0_darwin_arm64.tar.gz"
      sha256 "c341a810b79fc9dff3fd264dc9ddeb8f7e30575f589a1236633a3da48f662846"

      define_method(:install) do
        bin.install "goscaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.1.0/goscaffold_0.1.0_linux_amd64.tar.gz"
      sha256 "52c6b69a19a16673a46cf262cffd255027e272fe59dfb6e8dea058d75e3d587a"
      define_method(:install) do
        bin.install "goscaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.1.0/goscaffold_0.1.0_linux_arm64.tar.gz"
      sha256 "2e1b9074b6f884b7c2d2e3d6a2a4402af2ad4fc4530972d5ddcb1e602c203143"
      define_method(:install) do
        bin.install "goscaffold"
      end
    end
  end
end
