# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goscaffold < Formula
  desc "Scaffold Go projects with composable layers"
  homepage "https://github.com/jholm117/goscaffold"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.1.1/goscaffold_0.1.1_darwin_amd64.tar.gz"
      sha256 "a10cfde742d29b07cb8a0cbc3e023ac28d89bc902856011653e04fb806eb8fe7"

      define_method(:install) do
        bin.install "goscaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.1.1/goscaffold_0.1.1_darwin_arm64.tar.gz"
      sha256 "b2f2ba1d32bfa671f6ef51358de3f537f7ff2c8149b69c930ea0604a91c63f41"

      define_method(:install) do
        bin.install "goscaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.1.1/goscaffold_0.1.1_linux_amd64.tar.gz"
      sha256 "c85a6c02e70cac5148f08a56c161cc3a46aed5096446979c1c221cd035c20058"
      define_method(:install) do
        bin.install "goscaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.1.1/goscaffold_0.1.1_linux_arm64.tar.gz"
      sha256 "0fef0fdfbdb492c0bbf6a0c92c61549a68e3231d12e55aa43fc664b3f46781e3"
      define_method(:install) do
        bin.install "goscaffold"
      end
    end
  end
end
