# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goscaffold < Formula
  desc "Scaffold Go projects with composable layers"
  homepage "https://github.com/jholm117/goscaffold"
  version "0.2.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.2.10/goscaffold_0.2.10_darwin_amd64.tar.gz"
      sha256 "a86ae95efae5859c5b572c243fc3b6ad4b91812de25d2254a317cc86096e9962"

      define_method(:install) do
        bin.install "goscaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.2.10/goscaffold_0.2.10_darwin_arm64.tar.gz"
      sha256 "6e935ec992da9d44b98127dd6910e07d5c8a80bcbec53bec66863962559b3335"

      define_method(:install) do
        bin.install "goscaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.2.10/goscaffold_0.2.10_linux_amd64.tar.gz"
      sha256 "907537b66ded7d45ce8490a879fad575904144ba4b06227db02ae805f9e842d9"
      define_method(:install) do
        bin.install "goscaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.2.10/goscaffold_0.2.10_linux_arm64.tar.gz"
      sha256 "0bec3e9598e900b9dd2a747454039df3500bd9ab8d693eae2e5f0e9ed5c3f6d0"
      define_method(:install) do
        bin.install "goscaffold"
      end
    end
  end
end
