# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goscaffold < Formula
  desc "Scaffold Go projects with composable layers"
  homepage "https://github.com/jholm117/goscaffold"
  version "0.2.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.2.11/goscaffold_0.2.11_darwin_amd64.tar.gz"
      sha256 "6917482a69e94c82a907ca252fcb7d262e4832db52d071593cfdd13cdeb1c790"

      define_method(:install) do
        bin.install "goscaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.2.11/goscaffold_0.2.11_darwin_arm64.tar.gz"
      sha256 "07429a492e367e7c62002f40d3364df1663d9cc260f47f4b8395e204d76513fd"

      define_method(:install) do
        bin.install "goscaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.2.11/goscaffold_0.2.11_linux_amd64.tar.gz"
      sha256 "48ebd68289d8a849624e679f12fbc4da872c7b12b0d20d69afdc002cff2fe0ca"
      define_method(:install) do
        bin.install "goscaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jholm117/goscaffold/releases/download/v0.2.11/goscaffold_0.2.11_linux_arm64.tar.gz"
      sha256 "774b5334d5213ff24c93e45f5608dffa404e64c942f1f1b7115d61942b6cc917"
      define_method(:install) do
        bin.install "goscaffold"
      end
    end
  end
end
